### ISSUE TITLE
View of initial content

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#108] opened 2018-09-11 12:55 UTC
As a portal user I always want to be able to find out about the content of each cell

Dev Note: an additional tooltip in grey showing gen east or west (depending on the remaining space) should show the original uploaded content if a cell - if there had been a change

**Comment by dptolle** [comment] 2018-09-25 17:09
Duplicate of #109

**Closed** 2018-09-25 17:08 UTC
Labels: Story
